// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

// 

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAu6u49OS7TV32N3COd6FSttSU5OaVQ1Y',
    appId: '1:592032241711:web:a16d4b0106f4fff1558eda',
    messagingSenderId: '592032241711',
    projectId: 'hungry-app-e0743',
    authDomain: 'hungry-app-e0743.firebaseapp.com',
    storageBucket: 'hungry-app-e0743.appspot.com',
    measurementId: 'G-KRCHJE138J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo2ueX_QmyPYRmHxYcBjHIOJwWWacSwHk',
    appId: '1:592032241711:android:0b7c0aeb200b758b558eda',
    messagingSenderId: '592032241711',
    projectId: 'hungry-app-e0743',
    storageBucket: 'hungry-app-e0743.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNwKfr0cqmFAwG8fkpwn2n6B62d4E6Dgc',
    appId: '1:592032241711:ios:e61961cfbe494ff8558eda',
    messagingSenderId: '592032241711',
    projectId: 'hungry-app-e0743',
    storageBucket: 'hungry-app-e0743.appspot.com',
    iosBundleId: 'com.example.hungryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNwKfr0cqmFAwG8fkpwn2n6B62d4E6Dgc',
    appId: '1:592032241711:ios:e61961cfbe494ff8558eda',
    messagingSenderId: '592032241711',
    projectId: 'hungry-app-e0743',
    storageBucket: 'hungry-app-e0743.appspot.com',
    iosBundleId: 'com.example.hungryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAu6u49OS7TV32N3COd6FSttSU5OaVQ1Y',
    appId: '1:592032241711:web:83c927d178eb05de558eda',
    messagingSenderId: '592032241711',
    projectId: 'hungry-app-e0743',
    authDomain: 'hungry-app-e0743.firebaseapp.com',
    storageBucket: 'hungry-app-e0743.appspot.com',
    measurementId: 'G-L9RL3BYFZL',
  );
}
